# Generated by Django 4.2.1 on 2023-05-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_rename_status_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='gh ghg hghghjgjh ghj gh jghj'),
            preserve_default=False,
        ),
    ]
